---
# main playbook for deploy "k8s" by kubeadm-way

- name: main playbook for deploy "k8s" by kubeadm-way
  hosts: all
  become: yes
  
  tasks:
    - name: main task to run roles dinamicaly, besed on inventory vars
      include_role:
        name: "{{ item }}"
      loop: "{{ inventory_roles }}"
