apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccountName }}-ClusterRole
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccountName }}-ClusterRoleBinding
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.serviceAccountName }}-ClusterRole
  apiGroup: rbac.authorization.k8s.io
