apiVersion: v1
kind: Pod
metadata:
  name: nginx-distroless
  namespace: default
spec:
  containers:
    - name: nginx-distroless
      image: kyos0109/nginx-distroless
      ports:
        - containerPort: 80
