[kube_control_plane]
 k8s-master-01 ansible_host=111.88.240.145
 k8s-master-02 ansible_host=89.169.153.79
 k8s-master-03 ansible_host=111.88.250.158

[etcd:children]
kube_control_plane

[kube_node]
k8s-worker-01 ansible_host=51.250.84.153
k8s-worker-02 ansible_host=111.88.249.163
