apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubernetes-volumes-pvc
  namespace: homework
spec:
  storageClassName: homework-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi