---
# tasks file for deploy_app

- name: create project directory
  ansible.builtin.file:
    path: /opt/kuber-2026-05_homework/kubernetes-controllers
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy all k8s manifests for project
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/opt/kuber-2026-05_homework/kubernetes-controllers/{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - { src: "namespace.yaml", dest: "namespace.yaml", mode: "0644" }
    - { src: "deployment.yaml", dest: "deployment.yaml", mode: "0644" }

- name: deploy namespace.yaml in k3s cluster
  ansible.builtin.shell:
    cmd: kubectl apply -f /opt/kuber-2026-05_homework/kubernetes-controllers/namespace.yaml

- name: deploy deployment.yaml in k3s cluster
  ansible.builtin.shell:
    cmd: kubectl apply -f /opt/kuber-2026-05_homework/kubernetes-controllers/deployment.yaml